service: vimeo-upload-lambda # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 60
  deploymentBucket: execonline-serverless-deploy-archive

package:
  include:
    - node_modules/
    - package.json
    - .env
  exclude:
    - readme.md
    - event.json
    - config.json.*
    - .env.*
    - .babelrc

functions:
  entry:
    handler: handler.entry
    description: The new uploading lambda for vimeo
  test:
    handler: handler.test

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
